In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/buliding-density/validation_data_with_density.csv
/kaggle/input/buliding-density/training_data_with_density.csv
/kaggle/input/satellite-data/validation_data_with_satellite.csv
/kaggle/input/satellite-data/training_data_with_satellite.csv

In [4]:
# Feature Engineering
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Machine Learning
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

# Combine Datasets

In [5]:
train_density = pd.read_csv("/kaggle/input/buliding-density/training_data_with_density.csv")
train_density.head()

   Longitude   Latitude          datetime  UHI Index  density
0 -73.909167  40.813107  24-07-2021 15:53   1.030289        8
1 -73.909187  40.813045  24-07-2021 15:53   1.030289        8
2 -73.909215  40.812978  24-07-2021 15:53   1.023798        8
3 -73.909242  40.812908  24-07-2021 15:53   1.023798        8
4 -73.909257  40.812845  24-07-2021 15:53   1.021634        8

In [6]:
train_satellite = pd.read_csv("/kaggle/input/satellite-data/training_data_with_satellite.csv")
train_satellite.head()

,Longitude,Latitude,datetime,UHI Index,B01,B02,B03,B04,B05,B06,B07,B08,B8A,B11,B12,NDVI,NDBI,NDWI,LST
0,-73.909167,40.813107,24-07-2021 15:53,1.030289,825.0,990.0,1144.0,1172.0,1435.0,1688.0,1688.0,1830.0,1688.0,1788.0,1540.0,0.219187,-0.011609,-0.230666,38.393941
1,-73.909187,40.813045,24-07-2021 15:53,1.030289,825.0,990.0,1144.0,1172.0,1435.0,1688.0,1688.0,1830.0,1688.0,1788.0,1540.0,0.219187,-0.011609,-0.230666,38.393941
2,-73.909215,40.812978,24-07-2021 15:53,1.023798,825.0,622.0,785.0,744.0,1114.0,2006.0,2138.0,2318.0,2353.0,1566.0,1170.0,0.514043,-0.193615,-0.494038,37.785534
3,-73.909242,40.812908,24-07-2021 15:53,1.023798,825.0,619.0,750.0,738.0,1114.0,2006.0,2138.0,2302.0,2353.0,1566.0,1170.0,0.514474,-0.190279,-0.508519,37.785534
4,-73.909257,40.812845,24-07-2021 15:53,1.021634,825.0,556.0,758.0,660.0,1056.0,1891.0,2141.0,2280.0,2259.0,1658.0,1240.0,0.551020,-0.157948,-0.500987,37.358281

In [7]:
train_satellite = train_satellite.drop(["Longitude","Latitude","datetime","UHI Index"], axis=1)
train_concat = pd.concat([train_density, train_satellite], axis = 1)
train_concat.head()

,Longitude,Latitude,datetime,UHI Index,density,B01,B02,B03,B04,B05,B06,B07,B08,B8A,B11,B12,NDVI,NDBI,NDWI,LST
0,-73.909167,40.813107,24-07-2021 15:53,1.030289,8,825.0,990.0,1144.0,1172.0,1435.0,1688.0,1688.0,1830.0,1688.0,1788.0,1540.0,0.219187,-0.011609,-0.230666,38.393941
1,-73.909187,40.813045,24-07-2021 15:53,1.030289,8,825.0,990.0,1144.0,1172.0,1435.0,1688.0,1688.0,1830.0,1688.0,1788.0,1540.0,0.219187,-0.011609,-0.230666,38.393941
2,-73.909215,40.812978,24-07-2021 15:53,1.023798,8,825.0,622.0,785.0,744.0,1114.0,2006.0,2138.0,2318.0,2353.0,1566.0,1170.0,0.514043,-0.193615,-0.494038,37.785534
3,-73.909242,40.812908,24-07-2021 15:53,1.023798,8,825.0,619.0,750.0,738.0,1114.0,2006.0,2138.0,2302.0,2353.0,1566.0,1170.0,0.514474,-0.190279,-0.508519,37.785534
4,-73.909257,40.812845,24-07-2021 15:53,1.021634,8,825.0,556.0,758.0,660.0,1056.0,1891.0,2141.0,2280.0,2259.0,1658.0,1240.0,0.551020,-0.157948,-0.500987,37.358281

In [8]:
validation_density = pd.read_csv("/kaggle/input/buliding-density/validation_data_with_density.csv")
validation_density.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

   Longitude   Latitude  UHI Index  density
0 -73.971665  40.788763        NaN       12
1 -73.971928  40.788875        NaN       12
2 -73.967080  40.789080        NaN        4
3 -73.972550  40.789082        NaN       12
4 -73.969697  40.787953        NaN        9

In [9]:
validation_satellite = pd.read_csv("/kaggle/input/satellite-data/validation_data_with_satellite.csv")
validation_satellite.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Longitude,Latitude,UHI Index,B01,B02,B03,B04,B05,B06,B07,B08,B8A,B11,B12,NDVI,NDBI,NDWI,LST
0,-73.971665,40.788763,NaN,794.0,511.0,568.0,527.0,1112.0,2323.0,2649.0,2360.0,2784.0,1741.0,1218.0,0.634915,-0.150939,-0.612022,36.202990
1,-73.971928,40.788875,NaN,1221.0,494.0,661.0,497.0,1315.0,2652.0,2964.0,3662.0,3102.0,2124.0,1541.0,0.761000,-0.265814,-0.694194,36.202990
2,-73.967080,40.789080,NaN,1049.0,841.0,968.0,1056.0,1028.0,1418.0,1610.0,1402.0,1636.0,1634.0,1198.0,0.140765,0.076416,-0.183122,36.069687
3,-73.972550,40.789082,NaN,1189.0,903.0,984.0,1108.0,1971.0,1978.0,1970.0,1478.0,2049.0,2303.0,2219.0,0.143078,0.218196,-0.200650,36.886594
4,-73.969697,40.787953,NaN,1018.0,716.0,1046.0,917.0,1286.0,2382.0,2778.0,3038.0,2912.0,2102.0,1705.0,0.536283,-0.182101,-0.487757,34.500816

In [10]:
validation_satellite = validation_satellite.drop(["Longitude","Latitude","UHI Index"], axis=1)
validation_concat = pd.concat([validation_density, validation_satellite], axis=1)
validation_concat.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Longitude,Latitude,UHI Index,density,B01,B02,B03,B04,B05,B06,B07,B08,B8A,B11,B12,NDVI,NDBI,NDWI,LST
0,-73.971665,40.788763,NaN,12,794.0,511.0,568.0,527.0,1112.0,2323.0,2649.0,2360.0,2784.0,1741.0,1218.0,0.634915,-0.150939,-0.612022,36.202990
1,-73.971928,40.788875,NaN,12,1221.0,494.0,661.0,497.0,1315.0,2652.0,2964.0,3662.0,3102.0,2124.0,1541.0,0.761000,-0.265814,-0.694194,36.202990
2,-73.967080,40.789080,NaN,4,1049.0,841.0,968.0,1056.0,1028.0,1418.0,1610.0,1402.0,1636.0,1634.0,1198.0,0.140765,0.076416,-0.183122,36.069687
3,-73.972550,40.789082,NaN,12,1189.0,903.0,984.0,1108.0,1971.0,1978.0,1970.0,1478.0,2049.0,2303.0,2219.0,0.143078,0.218196,-0.200650,36.886594
4,-73.969697,40.787953,NaN,9,1018.0,716.0,1046.0,917.0,1286.0,2382.0,2778.0,3038.0,2912.0,2102.0,1705.0,0.536283,-0.182101,-0.487757,34.500816

# Select features

In [11]:
features = ['B01','B06','NDVI','NDBI','NDWI','LST','density']
train_df = train_concat[features + ["UHI Index"]]
train_df

,B01,B06,NDVI,NDBI,NDWI,LST,density,UHI Index
0,825.0,1688.0,0.219187,-0.011609,-0.230666,38.393941,8,1.030289
1,825.0,1688.0,0.219187,-0.011609,-0.230666,38.393941,8,1.030289
2,825.0,2006.0,0.514043,-0.193615,-0.494038,37.785534,8,1.023798
3,825.0,2006.0,0.514474,-0.190279,-0.508519,37.785534,8,1.023798
4,825.0,1891.0,0.551020,-0.157948,-0.500987,37.358281,8,1.021634
...,...,...,...,...,...,...,...,...
11224,432.0,2545.0,0.727473,-0.241216,-0.628594,30.293234,0,0.972470
11225,432.0,2545.0,0.766208,-0.303371,-0.659820,30.293234,0,0.972470
11226,432.0,2545.0,0.766208,-0.303371,-0.659820,30.440209,0,0.981124
11227,432.0,2545.0,0.766208,-0.303371,-0.659820,30.440209,0,0.981245
11228,432.0,2699.0,0.642043,-0.232831,-0.598456,30.440209,0,0.983408

# Remove duplicates from training data

In [12]:
# Remove duplicate rows from the DataFrame based on specified columns and keep the first occurrence
for col in features:
    # Check if the value is a numpy array and has more than one dimension
    train_df[col] = train_df[col].apply(lambda x: tuple(x) if isinstance(x, np.ndarray) and x.ndim > 0 else x)

# Now remove duplicates
uhi_data = train_df.drop_duplicates(subset=features, keep='first')
uhi_data.head()

<ipython-input-12-cc52a2d8b8e0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col] = train_df[col].apply(lambda x: tuple(x) if isinstance(x, np.ndarray) and x.ndim > 0 else x)

     B01     B06      NDVI      NDBI      NDWI        LST  density  UHI Index
0  825.0  1688.0  0.219187 -0.011609 -0.230666  38.393941        8   1.030289
2  825.0  2006.0  0.514043 -0.193615 -0.494038  37.785534        8   1.023798
3  825.0  2006.0  0.514474 -0.190279 -0.508519  37.785534        8   1.023798
4  825.0  1891.0  0.551020 -0.157948 -0.500987  37.358281        8   1.021634
6  825.0  1891.0  0.612442 -0.219765 -0.553026  37.358281        8   1.015143

In [13]:
uhi_data.shape

(9054, 8)

In [14]:
# Resetting the index of the dataset
uhi_data=uhi_data.reset_index(drop=True)

In [27]:
uhi_data.isna().sum()

B01          0
B06          0
NDVI         0
NDBI         0
NDWI         0
LST          0
density      0
UHI Index    0
dtype: int64

# Model Building

In [15]:
# Split the data into features (X) and target (y), and then into training and testing sets
X = uhi_data.drop(columns=['UHI Index']).values
y = uhi_data ['UHI Index'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=123)

**Feature Scaling**

In [16]:
# Scale the training and test data using standardscaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Model Training**

In [17]:
# Define the model
rf = RandomForestRegressor(random_state=42)

# Define the hyperparameter grid for RandomizedSearchCV
param_grid = {
    'n_estimators': [100, 200, 300, 500, 700, 900],          # Number of trees
    'max_depth': [None, 5, 10, 30, 50, 100],           # Maximum depth of trees
    'min_samples_split': [1, 2, 5, 10],             # Minimum samples required to split a node
    'min_samples_leaf': [1, 2, 4],                # Minimum samples required in a leaf node
    'max_features': ['auto', 'sqrt', 'log2', 0.1, 0.5],  # Number of features to consider for the best split
}

# Set up RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=rf,
                                   param_distributions=param_grid,
                                   n_iter=1000,           # Number of random combinations to test
                                   cv=5,                 # 5-fold cross-validation
                                   n_jobs=-1,            # Use all available cores
                                   verbose=2,            # Print progress
                                   random_state=42,      # For reproducibility
                                   scoring='r2')         # Use R-squared for scoring

# Fit the model
random_search.fit(X_train, y_train)

# Print the best hyperparameters found by RandomizedSearchCV
print("Best Hyperparameters found: ", random_search.best_params_)

# Retrieve the best model
best_rf = random_search.best_estimator_

# Print best model details
print(f"Best model has {best_rf.n_estimators} trees and max depth of {best_rf.max_depth}.")

Fitting 5 folds for each of 500 candidates, totalling 2500 fits

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning:
630 fits failed out of a total of 2500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
630 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py", line 340, in fit
    self._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of RandomForestRegressor must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.45689975        nan 0.39622833        nan 0.47086106 0.46950673
 0.52078162        nan 0.4354726         nan        nan 0.56583051
 0.54487779        nan 0.2477163  0.47223278 0.24783321        nan
 0.19668523 0.37722691        nan        nan 0.19647337 0.50712795
 0.19747392 0.42445018 0.35226496 0.19749664 0.47223278        nan
        nan 0.43507629 0.2306982         nan 0.45632172        nan
 0.47223278 0.42977972 0.36177833        nan 0.45440655 0.43270847
        nan 0.25894766 0.24785725 0.48262623 0.4594242         nan
 0.36177254        nan 0.50840793 0.45828027 0.4366497  0.41834939
 0.35866073 0.44450172 0.44543858 0.54786353        nan 0.40228958
 0.44409093 0.42437024 0.45974573        nan 0.41907668 0.50924399
 0.45619592 0.41834939 0.24746914 0.43270847        nan 0.41958171
 0.42002718 0.24753621 0.19711297        nan 0.48428838        nan
 0.35727021 0.41894261        nan 0.50712564 0.24792726 0.30387411
        nan 0.48376458 0.45632172 0.49785799 0.19678855 0.23186796
 0.42547262 0.25871407 0.4343053  0.35924435        nan 0.2313327
 0.47259402 0.24688586 0.39759634        nan        nan 0.23176919
 0.41474967 0.52971003        nan        nan 0.36160102        nan
 0.50755563        nan        nan 0.1968052  0.50755501 0.48517774
 0.43711496        nan 0.19811856 0.35318796 0.24783531 0.41281649
 0.19730219        nan 0.25804324 0.43373923 0.37753087 0.50840793
 0.45597973        nan 0.47259402        nan 0.47197025 0.52927798
 0.35220389        nan 0.448838          nan 0.38516925 0.2590814
 0.49667294        nan        nan        nan 0.50755563 0.55553296
 0.23048664        nan        nan 0.47278966 0.38513062        nan
 0.55553296 0.45565792 0.56585042 0.49672402 0.36160102 0.44516815
        nan 0.43826426 0.23175805 0.47223278        nan 0.48494816
 0.41907668 0.41441349 0.31361316 0.35220037 0.50924399 0.23157263
 0.39893443        nan 0.39553089 0.40004196        nan 0.44450172
 0.56302438 0.51957735        nan 0.45831457        nan        nan
 0.48222087        nan 0.52044736 0.35220389        nan 0.54140343
 0.41474967        nan 0.44409093 0.23140003 0.23131406 0.48574042
 0.38615937 0.39860311 0.4354726         nan 0.40205815 0.44513558
 0.4336373  0.38774266 0.31503622 0.41958171        nan 0.39860311
        nan        nan 0.36177833        nan 0.45828027        nan
 0.51999369 0.54362165 0.52973159        nan        nan        nan
 0.45562218        nan        nan 0.4315964         nan        nan
 0.49370706        nan 0.23183272        nan        nan 0.30364799
 0.38658494 0.38173426 0.41913148 0.3579104  0.50028785 0.54646229
 0.2312508  0.45956181 0.49874273 0.22985297        nan 0.25902111
 0.50857264 0.47234603        nan 0.35309533 0.50924399 0.25809646
        nan        nan 0.37659734 0.50619092 0.44450172 0.41958171
 0.49495994 0.4722241  0.47226111 0.4500154  0.4196202  0.23048664
 0.35682802 0.50633826 0.48214843 0.25856932 0.48376458        nan
 0.41894261 0.36276723 0.48461034 0.35817699 0.23225323 0.36546247
 0.30897564 0.45598443        nan 0.24784198 0.41474967        nan
 0.4500154  0.25851438 0.54263483 0.36367274        nan 0.19668523
 0.35573824        nan        nan        nan 0.36270269 0.45048066
 0.39764652 0.48261812 0.39999897 0.2320685  0.47086106        nan
 0.48214843 0.50619092 0.23227849 0.25946522 0.19811856        nan
 0.42002718        nan 0.3579104         nan 0.43268743 0.54140343
 0.51998006 0.45440655 0.22985297        nan 0.19667557        nan
 0.52044736 0.19743827        nan 0.47197025 0.42902858        nan
 0.39016244 0.23203445 0.43511131 0.49425332        nan 0.35318796
        nan        nan 0.4196202         nan 0.3884119  0.45565792
        nan 0.56505889        nan 0.49851826 0.41958171 0.50852188
 0.19790509 0.47271078 0.45598443 0.41401783 0.25939048 0.45833239
 0.4293923  0.43638397 0.48261812        nan 0.23067166 0.43477007
 0.41834939 0.48222087 0.23131406        nan        nan        nan
 0.2306982  0.35220389 0.49672402 0.36176639 0.48494816 0.47227955
 0.30067175 0.29912494        nan 0.38975097 0.24765711 0.41281649
        nan 0.35830879 0.41653365 0.25951754 0.35676584 0.42746265
 0.38483228 0.56302438 0.38843722 0.52815713 0.49672402 0.24804398
 0.47165581 0.30271469 0.56530178        nan 0.41609419 0.23152345
 0.41845042 0.23086388 0.3884119  0.3675893  0.45833239        nan
 0.5080578  0.45565792 0.52149984 0.49498853 0.37747232 0.48461034
 0.24788311 0.4315964  0.54133044 0.25809305 0.49876503 0.24788078
        nan 0.24783435        nan        nan 0.49495994 0.499856
 0.25906717        nan 0.47192343 0.41907668 0.35924435        nan
 0.29965717        nan 0.36315606 0.24688586 0.48461034 0.44490066
 0.4986472  0.48461034 0.46950673 0.2320189  0.23140003        nan
 0.43511131 0.39316545 0.43196004        nan 0.54263483        nan
 0.44041412        nan        nan 0.43477007 0.35318796 0.52927103
 0.45888766 0.23031799 0.41436652 0.45355442 0.45632172 0.24753196
 0.23186861        nan 0.35992781 0.35992781        nan 0.47086106
        nan        nan 0.35917154 0.3048275  0.49851826 0.4594242
 0.41431187        nan 0.24784198        nan 0.37740787 0.25862743
 0.41609419 0.50633942 0.25948294 0.45048066        nan 0.4594242
 0.45355442        nan 0.19799999 0.36294019 0.41442554 0.35794803
        nan 0.55404228 0.52927798 0.41907668 0.45809623 0.45927676
 0.30920513 0.37740787 0.43475701 0.45440655        nan 0.51999369
 0.4594242  0.51907357        nan 0.44409093 0.2476962  0.41958171
 0.45358283 0.19654416 0.47278966 0.24777659 0.36177833 0.39528022
        nan 0.39829148]
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(

Best Hyperparameters found:  {'n_estimators': 700, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'auto', 'max_depth': 50}
Best model has 700 trees and max depth of 50.

**Model Evaluation**

In [18]:
y_pred = best_rf.predict(X_test)
Y_test = y_test.tolist()
print("R² Score:", r2_score(Y_test, y_pred))

R² Score: 0.6173430122707977

# Submission

In [19]:
validation_concat.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Longitude,Latitude,UHI Index,density,B01,B02,B03,B04,B05,B06,B07,B08,B8A,B11,B12,NDVI,NDBI,NDWI,LST
0,-73.971665,40.788763,NaN,12,794.0,511.0,568.0,527.0,1112.0,2323.0,2649.0,2360.0,2784.0,1741.0,1218.0,0.634915,-0.150939,-0.612022,36.202990
1,-73.971928,40.788875,NaN,12,1221.0,494.0,661.0,497.0,1315.0,2652.0,2964.0,3662.0,3102.0,2124.0,1541.0,0.761000,-0.265814,-0.694194,36.202990
2,-73.967080,40.789080,NaN,4,1049.0,841.0,968.0,1056.0,1028.0,1418.0,1610.0,1402.0,1636.0,1634.0,1198.0,0.140765,0.076416,-0.183122,36.069687
3,-73.972550,40.789082,NaN,12,1189.0,903.0,984.0,1108.0,1971.0,1978.0,1970.0,1478.0,2049.0,2303.0,2219.0,0.143078,0.218196,-0.200650,36.886594
4,-73.969697,40.787953,NaN,9,1018.0,716.0,1046.0,917.0,1286.0,2382.0,2778.0,3038.0,2912.0,2102.0,1705.0,0.536283,-0.182101,-0.487757,34.500816

In [20]:
submission_val_data = validation_concat[features]
submission_val_data.head()

      B01     B06      NDVI      NDBI      NDWI        LST  density
0   794.0  2323.0  0.634915 -0.150939 -0.612022  36.202990       12
1  1221.0  2652.0  0.761000 -0.265814 -0.694194  36.202990       12
2  1049.0  1418.0  0.140765  0.076416 -0.183122  36.069687        4
3  1189.0  1978.0  0.143078  0.218196 -0.200650  36.886594       12
4  1018.0  2382.0  0.536283 -0.182101 -0.487757  34.500816        9

In [21]:
# Feature Scaling 
submission_val_data = submission_val_data.values
transformed_submission_data = sc.transform(submission_val_data)

In [22]:
#Making predictions
final_predictions = best_rf.predict(transformed_submission_data)
final_prediction_series = pd.Series(final_predictions)

In [23]:
#Combining the results into dataframe
submission_df = pd.DataFrame({'Longitude':validation_concat['Longitude'].values, 'Latitude':validation_concat['Latitude'].values, 'UHI Index':final_prediction_series.values})

In [24]:
#Displaying the sample submission dataframe
submission_df.head()

   Longitude   Latitude  UHI Index
0 -73.971665  40.788763   0.968101
1 -73.971928  40.788875   0.972441
2 -73.967080  40.789080   0.976972
3 -73.972550  40.789082   0.978955
4 -73.969697  40.787953   0.976413

In [25]:
#Dumping the predictions into a csv file.
submission_df.to_csv("submission.csv",index = False)